package com.example.minhaseconomias.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta para o Tema Claro (Light Theme)
val GreenPrimaryLight = Color(0xFF006D39)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFF9AF6B3)
val GreenOnPrimaryContainerLight = Color(0xFF00210D)
val GreenSecondaryLight = Color(0xFF4F6353)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFD2E8D4)
val GreenOnSecondaryContainerLight = Color(0xFF0D1F13)
val GreenTertiaryLight = Color(0xFF3C6472)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFBFE9FA)
val GreenOnTertiaryContainerLight = Color(0xFF001F28)
val GreenErrorLight = Color(0xFFBA1A1A)
val GreenOnErrorLight = Color(0xFFFFFFFF)
val GreenBackgroundLight = Color(0xFFFBFDF8)
val GreenOnBackgroundLight = Color(0xFF191C19)
val GreenSurfaceLight = Color(0xFFFBFDF8)
val GreenOnSurfaceLight = Color(0xFF191C19)

// Paleta para o Tema Escuro (Dark Theme)
val GreenPrimaryDark = Color(0xFF7EDA99)
val GreenOnPrimaryDark = Color(0xFF00391A)
val GreenPrimaryContainerDark = Color(0xFF005229)
val GreenOnPrimaryContainerDark = Color(0xFF9AF6B3)
val GreenSecondaryDark = Color(0xFFB7CCB8)
val GreenOnSecondaryDark = Color(0xFF223527)
val GreenSecondaryContainerDark = Color(0xFF384C3D)
val GreenOnSecondaryContainerDark = Color(0xFFD2E8D4)
val GreenTertiaryDark = Color(0xFFA3CEDC)
val GreenOnTertiaryDark = Color(0xFF063542)
val GreenTertiaryContainerDark = Color(0xFF234C59)
val GreenOnTertiaryContainerDark = Color(0xFFBFE9FA)
val GreenErrorDark = Color(0xFFFFB4AB)
val GreenOnErrorDark = Color(0xFF690005)
val GreenBackgroundDark = Color(0xFF191C19)
val GreenOnBackgroundDark = Color(0xFFE2E3DE)
val GreenSurfaceDark = Color(0xFF191C19)
val GreenOnSurfaceDark = Color(0xFFE2E3DE)